const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const http = require('node:http'); const { test } = require('node:test');
const load = require('./load-ts.cjs');
const { ArtifactsService, ArtifactLibraryService, RuntimeSettingsService, nodeRuntime, runLogged, command } = load(() => ({ ...require('../src/main/services/artifacts.ts'), ...require('../src/main/services/artifactLibrary.ts'), ...require('../src/main/services/runtimeSettings.ts'), ...require('../src/main/services/artifactProcess.ts') }));

test('real artifact installs, builds, serves shaped HTTP/WebSocket APIs on dynamic ports, and renders independent Playwright pages', { timeout: 480000 }, async(t) => {
  const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'skillz artifact integration ë ')));
  const library=new ArtifactLibraryService(path.join(root,'settings.json'),path.resolve(__dirname,'../artifact-template'),path.join(root,'contexts'));
  const service=new ArtifactsService(library,new RuntimeSettingsService(path.join(root,'runtime.json')),()=>{});
  let upstream;
  t.after(async()=>{await service.dispose();if(upstream)await new Promise(resolve=>upstream.close(resolve));assert.equal(fs.realpathSync(path.dirname(root)),fs.realpathSync(os.tmpdir()));assert.ok(path.basename(root).startsWith('skillz artifact integration ë '));fs.rmSync(root,{recursive:true,force:true,maxRetries:5});});
  await library.configure(path.join(root,'library'));
  const documents=path.join(root,'documents');fs.mkdirSync(documents);fs.writeFileSync(path.join(documents,'read ë.txt'),'Readable ë');
  const one=await library.create({title:'Schema ë',prompt:'Explore tables',sourceRoot:'',shareFacts:false,shareMemory:false,access:{directories:[{id:'documents',label:'Documents',path:fs.realpathSync(documents)}],allowWorkspaceRead:false}});
  const two=await library.create({title:'Code graph',prompt:'Explore dependencies',sourceRoot:'',shareFacts:false,shareMemory:false});
  const [a,b]=await Promise.all([service.start(one.id),service.start(two.id)]);
  assert.deepEqual((await (await fetch(`${a.url}/files/roots`)).json()).map(item=>item.id),['repo','documents']);
  assert.equal(await (await fetch(`${a.url}/files/documents/read?path=read%20%C3%AB.txt`)).text(),'Readable ë');
  assert.equal((await fetch(`${a.url}/files/documents/read?path=../settings.json`)).status,403);
  assert.equal((await fetch(`${a.url}/files/unknown/list`)).status,403);
  assert.equal((await fetch(`${a.url}/files/documents/read?path=read%20%C3%AB.txt`,{method:'POST'})).status,405);
  assert.equal((await fetch(`${b.url}/files/documents/list`)).status,403);
  assert.equal(a.status,'running');assert.equal(b.status,'running');assert.notEqual(a.url,b.url);
  let build=await command('docker',['exec',service.runtimes.get(one.id).sandbox.name,'npm','run','build'],one.root);
  assert.match(build,/built in/);
  let requests=0;
  upstream=http.createServer((req,res)=>{requests++;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({tables:['users','orders'],query:new URL(req.url,'http://localhost').searchParams.get('q')}));});
  await new Promise(resolve=>upstream.listen(0,'0.0.0.0',resolve));
  const target=`http://host.docker.internal:${upstream.address().port}`;
  const {WebSocketServer,WebSocket}=require('ws');
  const ws=new WebSocketServer({server:upstream});ws.on('connection',client=>client.on('message',data=>client.send(data)));t.after(()=>ws.close());
  const config={version:1,apis:[{id:'schema',transport:'http',url:target,method:'GET',requestSchema:{type:'object',properties:{q:{type:'string'}},required:['q'],additionalProperties:false},responseSchema:{type:'object',properties:{tables:{type:'array',items:{type:'string'}},query:{type:'string'}},required:['tables','query']}},{id:'events',transport:'websocket',url:target.replace('http:','ws:'),requestSchema:{type:'object',properties:{message:{type:'string'}},required:['message']},responseSchema:{type:'object',properties:{message:{type:'string'}},required:['message']}}]};
  await library.saveApis(one.id,config);
  assert.deepEqual(await (await fetch(`${a.url}/api/schema?q=all`)).json(),{tables:['users','orders'],query:'all'});
  const before=requests;assert.equal((await fetch(`${a.url}/api/schema`)).status,502);assert.equal(requests,before);
  assert.equal((await fetch(`${a.url}/api/unknown`)).status,404);
  assert.equal((await fetch(`${a.url}/api/schema`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,405);
  assert.equal((await fetch(`${a.url}/api/schema?q=all`,{headers:{Origin:'https://untrusted.example'}})).status,403);
  const socket=new WebSocket(`${a.url.replace('http:','ws:')}/ws/events`,{headers:{Origin:a.url}});
  await new Promise((resolve,reject)=>{socket.once('open',resolve);socket.once('error',reject)});
  const received=new Promise(resolve=>socket.once('message',value=>resolve(JSON.parse(value.toString()))));socket.send(JSON.stringify({message:'hello ë'}));assert.deepEqual(await received,{message:'hello ë'});socket.close();
  // Playwright here is the product service under test, not an alternative workbench automation harness.
  console.log('HTTP/WebSocket gateway and build verified; preparing preview browser.');
  await service.preview.installBrowser();
  const [frameA,frameB]=await Promise.all([service.frame(one.id),service.frame(two.id)]);
  assert.match(frameA.image,/^data:image\/jpeg;base64,/);assert.notEqual(frameA.image,frameB.image);
  assert.equal(service.preview.pages.size,2);
  await service.preview.input(one.id,{type:'key',key:'Tab'});
  await service.preview.input(one.id,{type:'key',key:'Enter'});
  assert.match(await service.preview.pages.get(one.id).page.locator('body').innerText(),/not shared yet/);
  assert.doesNotMatch(await service.preview.pages.get(two.id).page.locator('body').innerText(),/not shared yet/);
  assert.equal(await service.preview.pages.get(one.id).page.title(),'Schema ë');assert.equal(await service.preview.pages.get(two.id).page.title(),'Code graph');
  await service.preview.close(one.id);assert.equal(service.preview.pages.size,1);
  await service.stop(one.id);await assert.rejects(fetch(a.url));assert.equal((await fetch(b.url)).status,200);
});
