import { useEffect, useState } from 'react';
import { artifactApisSchema, type ArtifactApiConfig } from '../../../shared/artifacts';
const empty = (): ArtifactApiConfig => ({ id: '', title: '', transport: 'http', url: '', method: 'GET', requestSchema: {}, responseSchema: {}, headerEnv: {} });
export function ArtifactConnections({ id }: { id: string }): React.JSX.Element {
  const [apis, setApis] = useState<ArtifactApiConfig[]>([]); const [selected, setSelected] = useState(-1); const [draft, setDraft] = useState(empty); const [request, setRequest] = useState('{}'); const [response, setResponse] = useState('{}'); const [headers, setHeaders] = useState('{}'); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { let current = true; void window.workbench.artifacts.apis(id).then((config) => { if (current) setApis(config.apis); }).catch((error) => { if (current) setError(String(error)); }); return () => { current = false; }; }, [id]);
  function edit(index: number) { const api = apis[index] || empty(); setSelected(index); setDraft(api); setRequest(JSON.stringify(api.requestSchema, null, 2)); setResponse(JSON.stringify(api.responseSchema, null, 2)); setHeaders(JSON.stringify(api.headerEnv, null, 2)); setError(''); setNotice(''); }
  async function save(next: ArtifactApiConfig[]) { setBusy(true); setError(''); setNotice(''); try { const config = artifactApisSchema.parse({ version: 1, apis: next }); await window.workbench.artifacts.saveApis(id, config); setApis(config.apis); setNotice('Connections saved. New requests use these definitions.'); return true; } catch (error) { setError(String(error)); return false; } finally { setBusy(false); } }
  async function submit() { try { const value = { ...draft, requestSchema: JSON.parse(request), responseSchema: JSON.parse(response), headerEnv: JSON.parse(headers) }; const next = [...apis]; if (selected < 0) next.push(value); else next[selected] = value; if (await save(next)) setSelected(selected < 0 ? next.length - 1 : selected); } catch (error) { setError(`Invalid JSON: ${String(error)}`); } }
  return <div className="artifact-connections"><header><h2>API connections</h2><button onClick={() => edit(-1)}>New connection</button></header><p>Give each connection an ID and a JSON Schema for its inputs and outputs. The agent can also edit <code>.artifact/apis.json</code>.</p><div className="artifact-connection-list">{apis.map((api, index) => <button className={selected === index ? 'active' : ''} key={api.id} onClick={() => edit(index)}><strong>{api.title || api.id}</strong><code>/{api.transport === 'http' ? 'api' : 'ws'}/{api.id}</code></button>)}</div>{error && <p className="artifacts-error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<form onSubmit={(event) => { event.preventDefault(); void submit(); }}><div className="artifact-field-row"><label>Configuration ID<input required pattern="[a-z0-9][a-z0-9-]*" maxLength={64} value={draft.id} onChange={(event) => setDraft({ ...draft, id: event.target.value })} placeholder="schema" /></label><label>Label<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Database schema" /></label></div><div className="artifact-field-row"><label>Transport<select value={draft.transport} onChange={(event) => setDraft({ ...draft, transport: event.target.value as ArtifactApiConfig['transport'] })}><option value="http">HTTP / JSON</option><option value="websocket">WebSocket / JSON</option></select></label>{draft.transport === 'http' && <label>Method<select value={draft.method} onChange={(event) => setDraft({ ...draft, method: event.target.value as ArtifactApiConfig['method'] })}>{['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map((method) => <option key={method}>{method}</option>)}</select></label>}</div><label>Upstream URL<input required type="url" value={draft.url} onChange={(event) => setDraft({ ...draft, url: event.target.value })} placeholder={draft.transport === 'http' ? 'https://example.com/schema' : 'wss://example.com/events'} /></label><label>Request JSON Schema<textarea rows={5} spellCheck={false} value={request} onChange={(event) => setRequest(event.target.value)} /></label><label>Response JSON Schema<textarea rows={5} spellCheck={false} value={response} onChange={(event) => setResponse(event.target.value)} /></label><label>Headers from environment variables<textarea rows={3} spellCheck={false} value={headers} onChange={(event) => setHeaders(event.target.value)} placeholder={'{"Authorization":"SCHEMA_API_AUTH"}'} /></label><small>Map header names to environment variable names. Set secrets in the desktop process environment, then restart the artifact server.</small><div className="artifact-form-actions"><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save connection'}</button>{selected >= 0 && <button type="button" disabled={busy} onClick={() => { void save(apis.filter((_, index) => index !== selected)).then((ok) => { if (ok) edit(-1); }); }}>Remove connection</button>}</div></form></div>;
}
