import { useEffect, useMemo, useState } from 'react';
import { artifactApisSchema, type ArtifactApiConfig } from '../../../shared/artifacts';
import { artifactApiBlueprints, openApiToArtifactBlueprint } from '../../../shared/artifactBlueprints';

const empty = (): ArtifactApiConfig => artifactApisSchema.parse({ version: 1, apis: [{ id: 'new-request', title: '', transport: 'http', url: 'https://example.com', method: 'GET' }] }).apis[0];
export function ArtifactConnections({ id, running }: { id: string; running: boolean }): React.JSX.Element {
  const [apis, setApis] = useState<ArtifactApiConfig[]>([]); const [selected, setSelected] = useState(-1); const [draft, setDraft] = useState(empty);
  const [request, setRequest] = useState('{}'); const [response, setResponse] = useState('{}'); const [headers, setHeaders] = useState('{}'); const [example, setExample] = useState('{}'); const [tests, setTests] = useState('[]'); const [extract, setExtract] = useState('[]'); const [scripts, setScripts] = useState('[]');
  const [variables, setVariables] = useState('{}'); const [approveMutations, setApproveMutations] = useState(false); const [openApi, setOpenApi] = useState(''); const [showImport, setShowImport] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [result, setResult] = useState(''); const [busy, setBusy] = useState(false);
  const collections = useMemo(() => [...new Set(apis.filter(api => api.transport === 'http').map(api => api.collection))], [apis]);
  useEffect(() => { let current = true; void window.workbench.artifacts.apis(id).then(config => { if (current) setApis(config.apis); }).catch(error => { if (current) setError(String(error)); }); return () => { current = false; }; }, [id]);
  function edit(index: number) { const api = apis[index] || empty(); setSelected(index); setDraft(api); setRequest(JSON.stringify(api.requestSchema, null, 2)); setResponse(JSON.stringify(api.responseSchema, null, 2)); setHeaders(JSON.stringify(api.headerEnv, null, 2)); setExample(JSON.stringify(api.example, null, 2)); setTests(JSON.stringify(api.tests, null, 2)); setExtract(JSON.stringify(api.extract, null, 2)); setScripts(JSON.stringify(api.scripts, null, 2)); setError(''); setNotice(''); }
  async function save(next: ArtifactApiConfig[]) { setBusy(true); setError(''); setNotice(''); try { const config = artifactApisSchema.parse({ version: 1, apis: next }); await window.workbench.artifacts.saveApis(id, config); setApis(config.apis); setNotice(running ? 'Blueprints saved. The running preview reads updates automatically.' : 'Blueprints saved. Start the preview to run collections.'); return true; } catch (error) { setError(String(error)); return false; } finally { setBusy(false); } }
  async function submit() { try { const value = { ...draft, requestSchema: JSON.parse(request), responseSchema: JSON.parse(response), headerEnv: JSON.parse(headers), example: JSON.parse(example), tests: JSON.parse(tests), extract: JSON.parse(extract), scripts: JSON.parse(scripts) }; const next = [...apis]; if (selected < 0) next.push(value); else next[selected] = value; if (await save(next)) setSelected(selected < 0 ? next.length - 1 : selected); } catch (error) { setError(`Invalid JSON: ${String(error)}`); } }
  async function addBlueprint(blueprintId: string) { const blueprint = artifactApiBlueprints.find(item => item.id === blueprintId); if (!blueprint) return; const ids = new Set(apis.map(api => api.id)); if (blueprint.apis.some(api => ids.has(api.id))) { setError('This Blueprint is already installed.'); return; } await save([...apis, ...blueprint.apis]); }
  async function importOpenApi() { try { const blueprint = openApiToArtifactBlueprint(JSON.parse(openApi), 'openapi'); const ids = new Set(apis.map(api => api.id)); if (blueprint.apis.some(api => ids.has(api.id))) throw new Error('The converted request IDs conflict with existing requests.'); if (await save([...apis, ...blueprint.apis])) { setOpenApi(''); setShowImport(false); setNotice(`Imported ${blueprint.apis.length} requests from ${blueprint.title}.`); } } catch (error) { setError(`OpenAPI import failed: ${String(error)}`); } }
  async function runCollection(collection: string) { setBusy(true); setError(''); setResult(''); try { const output = await window.workbench.artifacts.runApiCollection(id, collection, JSON.parse(variables), approveMutations); setResult(JSON.stringify(output, null, 2)); } catch (error) { setError(String(error)); } finally { setBusy(false); } }
  return <div className="artifact-connections">
    <header><div><h2>API Blueprints</h2><p>Build request collections, tests, and artifact-specific Skillz commands.</p></div><button onClick={() => edit(-1)}>New request</button></header>
    <section className="artifact-blueprint-gallery"><strong>Quickstarts</strong><div>{artifactApiBlueprints.map(blueprint => <button key={blueprint.id} disabled={busy} onClick={() => void addBlueprint(blueprint.id)}><span>{blueprint.title}</span><small>{blueprint.description}</small></button>)}<button onClick={() => setShowImport(value => !value)}><span>Import OpenAPI</span><small>Convert supported HTTP operations into this format.</small></button></div>{showImport && <div className="artifact-openapi-import"><textarea rows={6} value={openApi} onChange={event => setOpenApi(event.target.value)} placeholder="Paste an OpenAPI JSON document" spellCheck={false} /><button disabled={!openApi.trim() || busy} onClick={() => void importOpenApi()}>Convert and add</button></div>}</section>
    <section className="artifact-collections"><header><strong>Collections</strong><small>Runs examples in order, extracts variables, and evaluates tests.</small></header>{collections.length ? collections.map(collection => <div key={collection}><code>{collection}</code><span>{apis.filter(api => api.collection === collection).length} requests</span><button disabled={!running || busy} onClick={() => void runCollection(collection)}>Run &amp; test</button></div>) : <p>No collections yet.</p>}<label>Collection variables (JSON)<textarea rows={3} value={variables} onChange={event => setVariables(event.target.value)} spellCheck={false} /></label><label><input type="checkbox" checked={approveMutations} onChange={event => setApproveMutations(event.target.checked)} /> Approve mutation requests for this run</label>{result && <pre>{result}</pre>}</section>
    <div className="artifact-connection-list">{apis.map((api, index) => <button className={selected === index ? 'active' : ''} key={api.id} onClick={() => edit(index)}><strong>{api.title || api.id}</strong><span><code>{api.collection}</code> · {api.commandKind || (api.method === 'GET' ? 'discovery' : 'mutation')}</span><code>/{api.transport === 'http' ? 'api' : 'ws'}/{api.id}</code></button>)}</div>
    {error && <p className="artifacts-error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    <form onSubmit={event => { event.preventDefault(); void submit(); }}>
      <div className="artifact-field-row"><label>Request ID<input required pattern="[a-z0-9][a-z0-9-]*" maxLength={64} value={draft.id} onChange={event => setDraft({ ...draft, id: event.target.value })} /></label><label>Label<input value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /></label><label>Collection<input required pattern="[a-z0-9][a-z0-9-]*" value={draft.collection} onChange={event => setDraft({ ...draft, collection: event.target.value })} /></label></div>
      <label>Description<input maxLength={500} value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} placeholder="What this command gives the agent" /></label>
      <div className="artifact-field-row"><label>Transport<select value={draft.transport} onChange={event => setDraft({ ...draft, transport: event.target.value as ArtifactApiConfig['transport'] })}><option value="http">HTTP / JSON</option><option value="websocket">WebSocket / JSON</option></select></label>{draft.transport === 'http' && <><label>Method<select value={draft.method} onChange={event => setDraft({ ...draft, method: event.target.value as ArtifactApiConfig['method'] })}>{['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map(method => <option key={method}>{method}</option>)}</select></label><label>Agent command type<select value={draft.commandKind || 'auto'} onChange={event => setDraft({ ...draft, commandKind: event.target.value === 'auto' ? undefined : event.target.value as 'discovery' | 'mutation' })}><option value="auto">Automatic from method</option><option value="discovery">Discovery</option><option value="mutation">Mutation</option></select></label></>}</div>
      <label>Upstream URL<input required type="url" value={draft.url} onChange={event => setDraft({ ...draft, url: event.target.value })} placeholder="https://example.com/repos/{{owner}}" /></label>
      <div className="artifact-json-grid"><label>Request JSON Schema<textarea rows={7} value={request} onChange={event => setRequest(event.target.value)} spellCheck={false} /></label><label>Response JSON Schema<textarea rows={7} value={response} onChange={event => setResponse(event.target.value)} spellCheck={false} /></label><label>Example input<textarea rows={5} value={example} onChange={event => setExample(event.target.value)} spellCheck={false} /></label><label>Headers from environment<textarea rows={5} value={headers} onChange={event => setHeaders(event.target.value)} spellCheck={false} placeholder={'{"Authorization":{"env":"SERVICE_TOKEN","prefix":"Bearer "}}'} /></label><label>Tests<textarea rows={5} value={tests} onChange={event => setTests(event.target.value)} spellCheck={false} placeholder={'[{"path":"data","operator":"exists"}]'} /></label><label>Extract variables<textarea rows={5} value={extract} onChange={event => setExtract(event.target.value)} spellCheck={false} placeholder={'[{"name":"itemId","path":"data.id"}]'} /></label><label>Collection scripts<textarea rows={6} value={scripts} onChange={event => setScripts(event.target.value)} spellCheck={false} placeholder={'[{"phase":"before","action":"set","name":"limit","value":10}]'} /></label></div>
      <small>Each HTTP request is advertised as <code>api_{draft.id.replace(/-/g, '_')}</code>. Secrets stay in the desktop environment; values are never written into the Blueprint.</small>
      <div className="artifact-form-actions"><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save request'}</button>{selected >= 0 && <button type="button" disabled={busy} onClick={() => { void save(apis.filter((_, index) => index !== selected)).then(ok => { if (ok) edit(-1); }); }}>Remove request</button>}</div>
    </form>
  </div>;
}
